FROM alpine:3.7

ADD dist/calico-upgrade ./calico-upgrade
ADD dist/kubectl-amd64 ./kubectl
ADD integration-snippets/node-init-container.sh ./
ADD integration-snippets/controller-init.sh ./
ADD integration-snippets/completion-job.sh ./

ENV CALICO_UPGRADE_CONTAINER=TRUE
ENV PATH=$PATH:/

WORKDIR /root
ENTRYPOINT ["/calico-upgrade"]
