FROM s390x/alpine:3.7

ADD dist/calico-upgrade-linux-s390x ./calico-upgrade
ADD dist/kubectl-s390x ./kubectl
ADD integration-snippets/node-init-container.sh ./
ADD integration-snippets/controller-init.sh ./
ADD integration-snippets/completion-job.sh ./

ENV CALICO_UPGRADE_CONTAINER=TRUE
ENV PATH=$PATH:/

WORKDIR /root
ENTRYPOINT ["/calico-upgrade"]
